added eks-service functionality

diff --git a/.github/workflows/terraform-plan-apply.yaml b/.github/workflows/terraform-plan-apply.yaml
--- a/.github/workflows/terraform-plan-apply.yaml
+++ b/.github/workflows/terraform-plan-apply.yaml
@@ -40,6 +40,11 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
+      - name: Configure EKS Cluster
+        if: ${{ inputs.eks-services == 'true' }}
+        run: |
+            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{inputs.eks-cluster}} || echo "Warning: Failed to update kubeconfig for EKS cluster ${{inputs.eks-cluster}}"
+
       - name: Terraform Init
         run: terraform init -input=false -backend=true
 
@@ -99,6 +104,11 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Configure EKS Cluster
+        if: ${{ inputs.eks-services == 'true' }}
+        run: |
+              aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{inputs.eks-cluster}} || echo "Warning: Failed to update kubeconfig for EKS cluster ${{inputs.eks-cluster}}"
 
       - name: Terraform Init
         run: terraform init -input=false -backend=true
